### ISSUE TITLE
dotfiles not using nullbrx/dotfiles 

### ISSUE THREAD

**Issue by finnstra** [jkmartindale/dotfiles#1]
Hello, your dotfiles don't use nullbrx/dotfiles. Could you try using that repo instead? 

Thanks!
-nullbrx

**Comment by jkmartindale** [comment]
Hacktoberfest is over

**Comment by jkmartindale** [comment]
![image](https://user-images.githubusercontent.com/11380394/142938385-23eb34ed-fcac-4f2e-8189-b6a2fdb49cf5.png)
